sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo chmod +x ./travis/before_test.sh
  - sudo chmod +x ./travis/gen-ssl.sh
  # update cmake to 2.8.12.2
  - yes | sudo add-apt-repository ppa:kubuntu-ppa/backports
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake
  # verify installed versions
  - which cmake
  - cmake --version
  - which g++
  - g++ -v
install:
  - sudo -E ./travis/before_test.sh
script:
  - export MYSQL_TEST_USER=root
  - export MYSQL_TEST_HOST=localhost
  - export MYSQL_TEST_PWD=
  - export MYSQL_TEST_DB=test
  - export MYSQL_TEST_PORT=3306
  - export MYSQL_TEST_SOCKET=/var/run/mysqld/mysqld.sock
  - mkdir build
  - cd build
  - /usr/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~
  - make
  - cd unittest/libmariadb
  - ctest -V
  - make install
env:
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M