version: 3.0.0;{build}
branches:
  only:
  - master
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_PARAM: 'Visual Studio 14 2015 Win64'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_PARAM: 'Visual Studio 14 2015'
configuration: RelWithDebInfo
platform: x64
clone_folder: c:\projects\mariadb-connector-c
services: mysql
before_build:
  - cmd: set MYSQL_TEST_USER=root
  - cmd: set MYSQL_TEST_HOST=127.0.0.1
  - cmd: set MYSQL_TEST_PASSWD=Password12!
  - cmd: "\"C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysql.exe\" -e \"create database test;\" --user=root --password=Password12!"
  - cmd: cmake -G "%CMAKE_PARAM%" -DCMAKE_BUILD_TYPE=RelWithDebInfo
build:
  project: mariadb-connector-c.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: cd c:\projects\mariadb-connector-c\unittest\libmariadb
  - cmd: ctest -V
